Add clippy to Circle CI.

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,217 +1,286 @@
 alias:
-  - &submodule
-    name: checkout_submodule
-    command: 'git submodule update --init'
 
-  - &save_build_cache
-    key: v2-cita-build-{{ .Environment.CIRCLE_SHA1 }}-sha3
+  - &restore-source-codes-cache
+    key: codes-{{ .Environment.CIRCLE_SHA1 }}
+
+  - &save-source-codes-cache
+    <<: *restore-source-codes-cache
+    paths: ~/cita-build
+
+  - &restore-dependencies-cache
+    key: deps-{{ checksum "Cargo.lock" }}
+
+  - &save-dependencies-cache
+    <<: *restore-dependencies-cache
+    paths:
+      - /opt/.cargo/git
+      - /opt/.cargo/registry
+
+  - &restore-clippy-cache
+    key: clippy-{{ .Environment.CIRCLE_BRANCH }}-{{ checksum "~/build-cache.key" }}
+    keys:
+      - clippy-{{ .Environment.CIRCLE_BRANCH }}-{{ checksum "~/build-cache.key" }}
+      - clippy-{{ .Environment.CIRCLE_BRANCH }}-
+      - clippy-
+      - build-
+
+  - &save-clippy-cache
+    <<: *restore-clippy-cache
     paths: ~/cita-build/target
 
-  - &save_cargo_cache
-    key: v2-deps-{{ checksum "Cargo.lock" }}-sha3
-    paths: /opt/.cargo
+  - &restore-security-audit-cache
+    key: audit-{{ checksum "/opt/.cargo/cargo-audit.version" }}
 
-  - &restore_build_cache
-    key: v2-cita-build-{{ .Environment.CIRCLE_SHA1 }}-sha3
+  - &save-security-audit-cache
+    <<: *restore-security-audit-cache
+    paths:
+      - /opt/.cargo/git
+      - /opt/.cargo/registry
 
-  - &restore_cargo_cache
-    key: v2-deps-{{ checksum "Cargo.lock" }}-sha3
+  - &before-restore-security-audit-cache
+    name: Before Restore Security Audit Cache
+    command: |
+        ver=$(cargo search cargo-audit | grep "^cargo-audit = " | awk '{ print $3 }' | tr -d '"')
+        date +"${ver}~%Y-%U" | tee /opt/.cargo/cargo-audit.version
 
-defaults: &defaults
+  - &restore-release-cache
+    key: release-{{ .Environment.CIRCLE_SHA1 }}
+
+  - &save-release-cache
+    <<: *restore-release-cache
+    paths: ~/cita-build/target/release-cache
+
+  - &before-save-release-cache
+    name: Before Save Release Cache
+    command: |
+        rm -rf target/release-cache
+        mv -vf target/install target/release-cache
+
+  - &after-restore-release-cache
+    name: After Restore Release Cache
+    command: |
+        rm -rf target/install
+        mv -vf target/release-cache target/install
+
+  - &restore-build-cache
+    key: build-{{ .Environment.CIRCLE_BRANCH }}-{{ checksum "~/build-cache.key" }}
+    keys:
+      - build-{{ .Environment.CIRCLE_BRANCH }}-{{ checksum "~/build-cache.key" }}
+      - build-{{ .Environment.CIRCLE_BRANCH }}-
+      - build-
+
+  - &save-build-cache
+    <<: *restore-build-cache
+    paths: ~/cita-build/target
+
+  - &before-restore-build-cache
+    name: Before Restore Build Cache
+    command: date +"%Y-%U" | tee ~/build-cache.key
+
+  - &before-save-build-cache
+    name: Before Save Build Cache
+    command: rm -rf target/install target/release-cache
+
+  - &clean-build-cache-if-too-large
+    name: Clean Cache If Too Large
+    command: |
+        target_mb=$(du -sm ~/cita-build/target/ | awk '{ print $1 }')
+        if [ ${target_mb} -gt 2048 ]; then
+            echo "[Info ] The target has ${target_mb} MiBytes data, CLEAN them."
+            cargo clean
+        else
+            echo "[Info ] The target has ${target_mb} MiBytes data, SKIP them."
+        fi
+
+  - &job-default
     docker:
-      - image: cita/cita-build:ubuntu-18.04-20180813
+      - image: cita/cita-build:ubuntu-18.04-20180820
     working_directory: ~/cita-build
     resource_class: large
 
+  - &job-unit-test
+    <<: *job-default
+    steps:
+      - restore_cache: *restore-source-codes-cache
+      - restore_cache: *restore-dependencies-cache
+      - run: *before-restore-build-cache
+      - restore_cache: *restore-build-cache
+      - run:
+          name: Replace Algorithms
+          command: |
+              ./scripts/replace_default_feature.sh ./ sha3hash ${HASH_ALGO}
+              ./scripts/replace_default_feature.sh ./ secp256k1 ${CRYPTO_ALGO}
+      - run:
+          name: Test Release
+          command: make test-release
+
 version: 2
 jobs:
-  build_sha3:
-    <<: *defaults
+
+  "Check Basic":
+    <<: *job-default
     steps:
       - checkout
-      - run: *submodule
       - run:
-          name: format
-          command: 'echo $CARGO_HOME; cargo fmt --all  -- --check'
-      - restore_cache:
-          key: security-audit-deps
+          name: Checkout SubModules
+          command: git submodule update --init
       - run:
-          name: security_audit
-          command: 'make security_audit'
-      - save_cache:
-          key: security-audit-deps
-          paths:
-            - /opt/.cargo
+          name: Check Format
+          command: make fmt
+      - save_cache: *save-source-codes-cache
+      - run: *before-restore-security-audit-cache
+      - restore_cache: *restore-security-audit-cache
       - run:
-          name: clean_security_audit
-          command: 'make clean'
-      - restore_cache: *restore_build_cache
-      - restore_cache: *restore_cargo_cache
+          name: Check Security Audit
+          command: make security_audit
+      - save_cache: *save-security-audit-cache
+
+  "Check Clippy":
+    <<: *job-default
+    steps:
+      - restore_cache: *restore-source-codes-cache
+      - restore_cache: *restore-dependencies-cache
+      - run: *before-restore-build-cache
+      - restore_cache: *restore-clippy-cache
       - run:
-          name: build
-          command: 'RUSTFLAGS="-F warnings" cargo build --release --all'
+          name: Check Clippy
+          command: make clippy
+      - run: *before-save-build-cache
+      - run: *clean-build-cache-if-too-large
+      - save_cache: *save-clippy-cache
+
+  "Release":
+    <<: *job-default
+    steps:
+      - restore_cache: *restore-source-codes-cache
+      - restore_cache: *restore-dependencies-cache
+      - run: *before-restore-build-cache
+      - restore_cache: *restore-build-cache
+      - run:
+          name: Build Release
+          command: make release
           no_output_timeout: 20m
+      - save_cache: *save-dependencies-cache
+      - run: *before-save-release-cache
+      - save_cache: *save-release-cache
+      - run: *before-save-build-cache
+      - run: *clean-build-cache-if-too-large
+      - save_cache: *save-build-cache
       - run:
-          name: check_cargolock
-          command: '[ $(git status --short Cargo.lock | wc -l) -ne 0 ] && echo "[Error] Please update Cargo.lock BEFORE commit." && git diff Cargo.lock && exit 1 || true'
-      - save_cache: *save_build_cache
-      - save_cache: *save_cargo_cache
+          name: Check Cargo.lock
+          command: |
+              if [ $(git status --short Cargo.lock | wc -l) -ne 0 ]; then
+                  echo "[Error] Please update Cargo.lock BEFORE commit."
+                  git diff Cargo.lock
+                  exit 1
+              fi
 
-  basic_test_sha3:
-    <<: *defaults
+  "Unit Test (sha3 & secp256k1)":
+    <<: *job-unit-test
+    environment:
+      HASH_ALGO: sha3hash
+      CRYPTO_ALGO: secp256k1
+
+  "Unit Test (blake2b & ed25519)":
+    <<: *job-unit-test
+    environment:
+      HASH_ALGO: blake2bhash
+      CRYPTO_ALGO: ed25519
+
+  "Unit Test (sm3 & sm2)":
+    <<: *job-unit-test
+    environment:
+      HASH_ALGO: sm3hash
+      CRYPTO_ALGO: sm2
+
+  "Integrate Test":
+    <<: *job-default
     steps:
-      - checkout
-      - run: *submodule
-      - restore_cache: *restore_build_cache
-      - restore_cache: *restore_cargo_cache
+      - restore_cache: *restore-source-codes-cache
+      - restore_cache: *restore-release-cache
+      - run: *after-restore-release-cache
       - run:
-          name: test
-          command: 'RUSTFLAGS="-F warnings" cargo test --release --tests'
+          name: Basic Integrate Test
+          command: ./tests/integrate_test/cita_basic.sh
+      - run:
+          name: JSON-RPC Mock Test in Quota Mode
+          command: ./tests/integrate_test/cita_jsonrpc_schema_mock.sh quota
+      - run:
+          name: (Skip & TODO) JSON-RPC Mock Test in Charge Mode
+          command: |
+              echo "We should add it back later."
+              # ./tests/integrate_test/cita_jsonrpc_schema_mock.sh charge
+      - run:
+          name: Test Transfer Value in Charge Mode
+          command: ./tests/integrate_test/cita_charge_mode.sh
 
-  basic_test_blake2b:
-    <<: *defaults
+  "Byzantine Test":
+    <<: *job-default
     steps:
-      - checkout
-      - run: *submodule
-      - restore_cache: *restore_build_cache
-      - restore_cache: *restore_cargo_cache
+      - restore_cache: *restore-source-codes-cache
+      - restore_cache: *restore-release-cache
+      - run: *after-restore-release-cache
       - run:
-          name: replace_hash
-          command: ./scripts/replace_default_feature.sh ./ sha3hash blake2bhash
+          name: Byzantine Test in Quota Mode
+          command: ./tests/integrate_test/cita_byzantinetest.sh quota
       - run:
-          name: replace_crypt
-          command: ./scripts/replace_default_feature.sh ./ secp256k1 ed25519
-      - run:
-          name: test
-          command: 'RUSTFLAGS="-F warnings" cargo test --release --tests'
+          name: Byzantine Test in Charge Mode
+          command: ./tests/integrate_test/cita_byzantinetest.sh charge
 
-  basic_test_sm3:
-    <<: *defaults
+  "Crosschain Test":
+    <<: *job-default
     steps:
-      - checkout
-      - run: *submodule
-      - restore_cache: *restore_build_cache
-      - restore_cache: *restore_cargo_cache
+      - restore_cache: *restore-source-codes-cache
+      - restore_cache: *restore-release-cache
+      - run: *after-restore-release-cache
       - run:
-          name: replace_hash
-          command: ./scripts/replace_default_feature.sh ./ sha3hash sm3hash
-      - run:
-          name: replace_crypt
-          command: ./scripts/replace_default_feature.sh ./ secp256k1 sm2
-      - run:
-          name: test
-          command: 'RUSTFLAGS="-F warnings" cargo test --release --tests'
+          name: Crosschain Test
+          command: ./tests/integrate_test/cita_crosschain.sh
 
-  # basic_test_coverage_sha3:
-  #   <<: *defaults
-  #   steps:
-  #     - restore_cache: *resotre_build_cache
-  #     - restore_cache: *restore_cargo_cache
-  #     - run:
-  #         name: test-coverage
-  #         command: |
-  #           bash <(curl https://raw.githubusercontent.com/xd009642/tarpaulin/master/travis-install.sh)
-  #           cargo tarpaulin \
-  #             --packages cita-auth \
-  #             --packages cita-jsonrpc \
-  #             --packages cita-chain \
-  #             --packages core \
-  #             --packages common-types \
-  #             --packages cita-bft \
-  #             --packages cita-network \
-  #             --packages cita-executor \
-  #             --packages core-executor \
-  #             --packages cita-forever \
-  #             --packages jsonrpc_types \
-  #             --skip-clean --coveralls ${COVERALLS_TOKEN}
-
-  integrate_test_sha3:
-    <<: *defaults
+  "Robustness Test":
+    <<: *job-default
     steps:
-      - checkout
-      - run: *submodule
-      - restore_cache: *restore_build_cache
+      - restore_cache: *restore-source-codes-cache
+      - restore_cache: *restore-release-cache
+      - run: *after-restore-release-cache
       - run:
-          name: config
-          command: './scripts/release.sh release'
-      - run:
-          name: basic
-          command: './tests/integrate_test/cita_basic.sh'
-      - run:
-          # EconomicalModel == Quota
-          name: jsonrpc-mock-tests-quota
-          command: './tests/integrate_test/cita_jsonrpc_schema_mock.sh quota'
-      # TODO: We should add it back later
-      # - run:
-          # EconomicalModel == Charge
-          # name: jsonrpc-mock-tests-charge
-          # command: './tests/integrate_test/cita_jsonrpc_schema_mock.sh charge'
-      - run:
-          name: economical-mode-charge-transfer-value
-          command: './tests/integrate_test/cita_charge_mode.sh'
-      - run:
-          name: robustness-test
-          command: './tests/integrate_test/robustness_test.py'
-
-
-  cita_byzantinetest:
-    <<: *defaults
-    steps:
-      - checkout
-      - run: *submodule
-      - restore_cache: *restore_build_cache
-      - run:
-          name: config
-          command: './scripts/release.sh release'
-      - run:
-          # EconomicalModel == Quota
-          name: byzantine-quota
-          command: './tests/integrate_test/cita_byzantinetest.sh quota'
-      - run:
-          # EconomicalModel == Charge
-          name: byzantine-charge
-          command: './tests/integrate_test/cita_byzantinetest.sh charge'
-
-  integrate_test_crosschain_sha3:
-    <<: *defaults
-    steps:
-      - checkout
-      - run: *submodule
-      - restore_cache: *restore_build_cache
-      - run:
-          name: config
-          command: './scripts/release.sh release'
-      - run:
-          name: crosschain
-          command: './tests/integrate_test/cita_crosschain.sh'
+          name: Robustness Test
+          command: ./tests/integrate_test/robustness_test.py
 
 workflows:
   version: 2
-  build-and-test:
+  "Build & Test":
     jobs:
-      - build_sha3
-      - basic_test_sha3:
+
+      - "Check Basic"
+
+      - "Check Clippy":
           requires:
-            - build_sha3
-      # - basic_test_coverage_sha3:
-      #     requires:
-      #       - build_sha3
-      - integrate_test_sha3:
+            - "Check Basic"
+      - "Release":
           requires:
-            - build_sha3
-      - cita_byzantinetest:
+            - "Check Basic"
+
+      - "Unit Test (sha3 & secp256k1)":
           requires:
-            - build_sha3
-      - integrate_test_crosschain_sha3:
+            - "Release"
+
+      - "Integrate Test":
           requires:
-            - build_sha3
-      - basic_test_blake2b:
+            - "Release"
+      - "Byzantine Test":
           requires:
-            - basic_test_sha3
-            - integrate_test_sha3
-            - integrate_test_crosschain_sha3
-      - basic_test_sm3:
+            - "Release"
+      - "Crosschain Test":
           requires:
-            - basic_test_sha3
-            - integrate_test_sha3
-            - integrate_test_crosschain_sha3
+            - "Release"
+     #- "Robustness Test":
+     #    requires:
+     #      - "Release"
+
+      - "Unit Test (blake2b & ed25519)":
+          requires:
+            - "Unit Test (sha3 & secp256k1)"
+      - "Unit Test (sm3 & sm2)":
+          requires:
+            - "Unit Test (sha3 & secp256k1)"
